name: Server

run-name: "Build and test the server component for commmit: ${{ github.event.head_commit.message }}" 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# Server is on subfolder "Server"
defaults:
  run:
    working-directory: ./Server

jobs:

  # Build job will build the project as well as
  # run unit tests.
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
